version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aiohttp
  - dependency-name: falcon
  - dependency-name: gunicorn
  - dependency-name: httpie
  - dependency-name: sanic
  - dependency-name: starlette
  - dependency-name: trinket
  - dependency-name: uvicorn
  - dependency-name: uvloop
