version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sanic
    versions:
    - 20.12.1
    - 20.12.2
    - 21.3.1
    - 21.3.2
  - dependency-name: aiofile
    versions:
    - 3.3.3
    - 3.4.0
  - dependency-name: uvloop
    versions:
    - 0.15.0
    - 0.15.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: uvicorn
    versions:
    - 0.13.3
  - dependency-name: aiohttp
    versions:
    - 3.7.3
  - dependency-name: starlette
    versions:
    - 0.14.1
  - dependency-name: httpie
    versions:
    - 2.3.0
