stages:
- python36
- python37
- python38

python36:
  stage: python36
  image: python:3.6
  script:
  - py.test

python37:
  stage: python37
  image: python:3.7
  script:
  - py.test

python38:
  stage: python38
  image: python:3.8
  script:
  - py.test

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - pip install -r requirements-dev.txt
  - python setup.py develop
