language: python
sudo: required
dist: xenial
python:
- 3.6
- 3.7
install:
- python setup.py develop
- pip install -r requirements-dev.txt
script: py.test -vv
branches:
  only:
    - master
notifications:
  email:
    on_failure: always
    on_success: never
