language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements-dev.txt
- make init
- make compile
- python setup.py develop
script: py.test -vv
branches:
  only:
    - master
notifications:
  email:
    on_failure: always
    on_success: never
